[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[runner]
fastRerenderThreshold = 1000

[env]
STREAMLIT_DEPLOYMENT = "true"
